"""
sql_guardrails.py

Validates SQL generated by the Data Retrieval agent BEFORE it ever touches
the database. This is the guardrail from the project brief: read-only,
schema-bounded query validation.

Deliberately dependency-free (no sqlparse) and deliberately conservative —
false positives (rejecting a safe query) are fine, false negatives (letting
an unsafe query through) are not.

Checks, in order:
  1. Exactly one statement (reject stacked/multi-statement queries)
  2. Statement must start with SELECT or WITH ... SELECT (read-only)
  3. No write/DDL/DML/admin keywords anywhere in the query
  4. No SQLite-specific escape hatches (ATTACH, PRAGMA)
  5. Every table referenced (after FROM/JOIN) must be in the schema allowlist
  6. Result set size is capped by wrapping in a LIMIT if the query doesn't
     already have one — enforced by the caller (retrieval_agent.py) at
     execution time, not here, since that requires actually running it.
"""

import re
from dataclasses import dataclass, field

# Schema allowlist — must match data/business.db. Update this if the schema
# in generate_synthetic_data.py changes.
ALLOWED_TABLES = {
    "dim_date", "dim_product", "dim_region", "dim_channel", "dim_segment",
    "fact_sales", "fact_returns", "fact_marketing_spend", "fact_finance_ops",
}

# Keywords that indicate a write, schema change, or admin operation.
# Matched as whole words, case-insensitive.
FORBIDDEN_KEYWORDS = {
    "insert", "update", "delete", "drop", "alter", "create", "replace",
    "truncate", "grant", "revoke", "vacuum", "attach", "detach", "pragma",
    "reindex", "analyze",
}

MAX_ROW_LIMIT = 1000  # hard cap enforced by retrieval_agent.py at execution time


@dataclass
class ValidationResult:
    is_valid: bool
    reason: str = ""
    tables_referenced: set = field(default_factory=set)


def _strip_comments(sql: str) -> str:
    sql = re.sub(r"--.*?$", " ", sql, flags=re.MULTILINE)
    sql = re.sub(r"/\*.*?\*/", " ", sql, flags=re.DOTALL)
    return sql


def _extract_tables(sql: str) -> set:
    # naive but adequate for our fixed schema: anything after FROM or JOIN
    pattern = re.compile(r"\b(?:FROM|JOIN)\s+([a-zA-Z_][a-zA-Z0-9_]*)", re.IGNORECASE)
    return {m.lower() for m in pattern.findall(sql)}


def _extract_cte_names(sql: str) -> set:
    # names defined by a WITH clause (e.g. "WITH monthly AS (...)," or
    # ", recent AS (...)") are not real tables and shouldn't be checked
    # against the schema allowlist
    pattern = re.compile(
        r"(?:\bWITH\s+|,\s*)([a-zA-Z_][a-zA-Z0-9_]*)\s+AS\s*\(", re.IGNORECASE
    )
    return {m.lower() for m in pattern.findall(sql)}


def validate_sql(sql: str) -> ValidationResult:
    if not sql or not sql.strip():
        return ValidationResult(False, "Empty query.")

    cleaned = _strip_comments(sql).strip()

    # 1. reject multiple statements (allow one optional trailing semicolon)
    body = cleaned[:-1] if cleaned.endswith(";") else cleaned
    if ";" in body:
        return ValidationResult(False, "Multiple statements are not allowed.")

    # 2. must be a read-only SELECT (optionally preceded by a WITH clause)
    head = body.strip().lower()
    if not (head.startswith("select") or head.startswith("with")):
        return ValidationResult(False, "Query must start with SELECT or WITH.")
    if head.startswith("with") and "select" not in head:
        return ValidationResult(False, "WITH clause must contain a SELECT.")

    # 3. forbidden keywords anywhere in the query
    tokens = set(re.findall(r"[a-zA-Z_]+", body.lower()))
    hit = tokens & FORBIDDEN_KEYWORDS
    if hit:
        return ValidationResult(False, f"Forbidden keyword(s) found: {', '.join(sorted(hit))}.")

    # 4. table allowlist (CTE names defined by this query's own WITH clause
    #    are not real tables and are excluded from the check)
    tables = _extract_tables(body)
    cte_names = _extract_cte_names(body)
    unknown = tables - ALLOWED_TABLES - cte_names
    if unknown:
        return ValidationResult(
            False,
            f"Query references table(s) not in the schema allowlist: {', '.join(sorted(unknown))}.",
            tables_referenced=tables,
        )
    if not tables:
        return ValidationResult(False, "Could not identify any known table in the query.")

    return ValidationResult(True, "OK", tables_referenced=tables)


def enforce_row_limit(sql: str, max_rows: int = MAX_ROW_LIMIT) -> str:
    """Wraps the query so it can never return more than max_rows, regardless
    of whether the generated SQL included its own LIMIT clause."""
    cleaned = sql.strip().rstrip(";")
    return f"SELECT * FROM ({cleaned}) AS _capped LIMIT {max_rows}"
